function list_subfolders( Exp )
%LIST_SUBFOLDERS Lists folders to analyse for specific germcell
%   germcell is a string, either of the five: P0, P1, P2, P3 or P4
    parentDirectory = ['/Users/hubats01/Desktop/P_lineage_analysis/',...
                        Exp.imageType, '/',...
                        Exp.imageType,'_',Exp.segmentationMode, '/',...
                        Exp.imageType,'_',Exp.segmentationMode, '_', ...
                        Exp.treatment, '_', Exp.protein, '/', ...
                        Exp.imageType,'_',Exp.segmentationMode, '_', ...
                        Exp.treatment, '_', Exp.protein, '_', Exp.germcell, '_', ... 
                        Exp.line, '_', Exp.temperature, '_', Exp.microscopeMode, '_', ...
                        Exp.suffix ];
    subfolderStrings = strsplit(genpath(parentDirectory),':');
    subfolderIndices = strncmp(cellfun(@fliplr, subfolderStrings, ...
                               'UniformOutput', false), 'sis', 3);
    subfolders = subfolderStrings(subfolderIndices);
    subfolders = cellfun(@(x) x(1:end-9), subfolders, 'UniformOutput', false);
    Exp.subfolders = subfolders;
end

